- Arithmetic Operations in Numpy
- Functions in Numpy
- where()
- abs()
- concatenate()
- stack
- split
- array_split()

### Arithmetic Operations in Numpy

- add()
- subtract()
- multiply()
- divide()

In [7]:
import numpy as np

s1 =np.array([1,2,3,4,5])

s2 =np.array([6,7,8,9,10])




In [8]:
s1

array([1, 2, 3, 4, 5])

In [9]:
s2

array([ 6,  7,  8,  9, 10])

### add()

In [10]:
np.add(s1,s2)

array([ 7,  9, 11, 13, 15])

### Functions in Numpy 

- sum
- mean(avg)
- std
- var
- exp
- log
- sqrt

#### example

In [11]:
arr=np.array([10,20,30,40])

arr

array([10, 20, 30, 40])

#### sum()

In [12]:
arr.sum()

100

#### mean()

In [13]:
arr.mean()

25.0

#### std()

In [15]:
np.sqrt([1,2,3,4])

array([1.        , 1.41421356, 1.73205081, 2.        ])

#### log()

In [16]:
np.log([3,4,5,6,7])

array([1.09861229, 1.38629436, 1.60943791, 1.79175947, 1.94591015])

In [17]:
np.var([3,4,5,6,7])

2.0

In [18]:
np.exp([3,4,5,6,7])

array([  20.08553692,   54.59815003,  148.4131591 ,  403.42879349,
       1096.63315843])

### where()

- The np.where function returns elements from two arrays based on a condition. 
- It selects elements from the first array where the condition is True and from the second array where the condition is False.

#### syntax

In [31]:
t1 =np.array([1,2,3,4,5])

t2 =np.array([6,7,8,9,10])



z=np.where(t1>2,t1,t2)

z

# t1>2


array([6, 7, 3, 4, 5])

In [27]:
a = np.arange(10)
arange

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [28]:
np.where(a < 5, a, 10*a)

array([ 0,  1,  2,  3,  4, 50, 60, 70, 80, 90])

### abs()

#### example

In [32]:
abs(-10)

10

In [35]:
t3 =np.array([6,7,-8,9,-10,-10])

t3

array([  6,   7,  -8,   9, -10, -10])

In [36]:
abs(t3)

array([ 6,  7,  8,  9, 10, 10])

## concatenate()

In [37]:
n1 =np.array([1,2,3,4,5])

n2 =np.array([6,7,8,9,10])

In [39]:
np.concatenate((n1,n2))

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

### stack

In [40]:
A =np.array([1,2,3,4,5])

B =np.array([6,7,8,9,10])

In [41]:
q=np.stack((A,B))
                           # Stacks arrays A and B along the specified axis
q

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [46]:
q1=np.stack((A,B),axis=1)
                           # Stacks arrays A and B along the specified axis
q1

array([[ 1,  6],
       [ 2,  7],
       [ 3,  8],
       [ 4,  9],
       [ 5, 10]])

### split

In [56]:

arr = np.array([1, 2, 3, 4, 5, 6,7,8,9,10]) 

newarr = np.split(arr, 2)   

print(newarr) 

[array([1, 2, 3, 4, 5]), array([ 6,  7,  8,  9, 10])]


In [57]:
arr1 = np.array([1, 2, 3, 4, 5, 6,7,8,9,10]) 

newarr1 = np.split(arr, 6)   

print(newarr1)

ValueError: array split does not result in an equal division

### array_split()

In [62]:
arr2 = np.array([1, 2, 3, 4, 5, 6,7,8,9,10]) 

newarr2 = np.array_split(arr, 6)   

print(newarr2)

[array([1, 2]), array([3, 4]), array([5, 6]), array([7, 8]), array([9]), array([10])]


In [2]:
#+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++=

# Pandas

### Pandas is a Python library used for working with data sets.

#### It has functions for analyzing, cleaning, exploring, and manipulating data.

- Pandas allows us to analyze big data and make conclusions based on statistical theories.

- Pandas can clean messy data sets, and make them readable and relevant.

- Relevant data is very important in data science.

### Pandas Data Structure

- Series (1 Dimensional)
- DataFrame (2 Dimensional)

### Series (1 Dimensional)

A Series is a one-dimensional labeled array in pandas. It can hold data of various types, including integers, floats, strings, and more.

### Rename

#### syntax

### replace()

#### replace single value

#### replace Multiple values

### sort_index()

### sort_values()