- list comprehension
- Numpy Introduction

## list comprehension

- list comprehension is an elegant way to define and create listed based on exsting lists.
- list comprehension is generally more compact and faster than normal functions and loops for creating list.
- list comprehension offers a shorter syntax when you want to create a new list based on the values of an exsting list.

#### syntax

#### without using list comprehension example

In [1]:
newlist =[] #empty list


old_list =["apple","orange","banana","cherry"]

for i in old_list:
    if "a" in i:
        newlist.append(i)
print(newlist)   

['apple', 'orange', 'banana']


#### with list comprehension example

In [2]:
# example

list1 =["apple","orange","banana","cherry"]


[j for j in list1 if "a" in j]

['apple', 'orange', 'banana']

### example2

In [3]:
# example

[k for k in range(1,11)]

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

### example3

In [4]:
# example


lst = [1,2,3,4,5,6,7,8,9,10]


lst

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [7]:
[v if v%2==0 else v+2 for v in lst]

[3, 2, 5, 4, 7, 6, 9, 8, 11, 10]

In [4]:
#+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

# Numpy Introduction

- NumPy is a Python library created in 2005 that performs numerical calculations. It is generally used for working with arrays.

- NumPy also includes a wide range of mathematical functions, such as linear algebra, Fourier transforms, and random number generation, which can be applied to arrays.

### What is NumPy Used for?

- Machine Learning
- Data Science
- Image and Signal Processing
- Scientific Computing

#### import library

In [8]:
import numpy as np

In [9]:
a = np.array([1,2,3,4,5])

a

array([1, 2, 3, 4, 5])

In [10]:
type(a)

numpy.ndarray

#### check dimension

In [ ]:
#syntax

np.ndim(variable_name)

In [11]:
#example

np.ndim(a)

1

In [12]:
a2 =np.array([[[10]]])

a2

array([[[10]]])

In [13]:
np.ndim(a2)

3

#### indexing

In [14]:
a

array([1, 2, 3, 4, 5])

In [16]:
a[2]

3

#### slicing

In [19]:
a[1:4:2]

array([2, 4])

### Array creation

- 0_D array
- 1_D array
- 2_D array
- 3_D array

### 0 dimension array

In [20]:
arr1 =np.array(80)

arr1

array(80)

In [21]:
np.ndim(arr1)

0

### 1 dimensional array

In [22]:
arr2 = np.array([10,20,30,40])

arr2

array([10, 20, 30, 40])

### 2 dimensional array

In [23]:
arr3 =np.array([[1,2,3,4],[5,6,7,8]])

arr3

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [24]:
np.ndim(arr3)

2

In [25]:
########

### arange()

#### syntax

#### example

In [31]:
np.arange(1,51)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50])

### reshape()

#### syntax

#### example

In [38]:
np.arange(1,11)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [39]:
np.arange(1,11).reshape(5,2)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [35]:
np.arange(1,11).reshape(2,5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [37]:
np.arange(1,21).reshape(4,5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

### Array creation using zeros

### zeros()

#### syntax

#### example

In [40]:
np.zeros((5,8))

array([[0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.]])

In [43]:
np.zeros((5,8),dtype=int)

array([[0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0]])

### ones

In [ ]:
np.ones()

np.ones((row,col))

#### example

In [44]:
np.ones((5,8))

array([[1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.]])

In [45]:
np.ones((5,8),int)

array([[1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1]])

In [46]:
np.ones((5,8),bool)

array([[ True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True]])

### full

In [ ]:
# syntax

np.full((row,col),value)

In [51]:
# example

np.full((5,8),20)

array([[20, 20, 20, 20, 20, 20, 20, 20],
       [20, 20, 20, 20, 20, 20, 20, 20],
       [20, 20, 20, 20, 20, 20, 20, 20],
       [20, 20, 20, 20, 20, 20, 20, 20],
       [20, 20, 20, 20, 20, 20, 20, 20]])

In [52]:
#########################################################################

## Random Module

- randrange()
- randint()
- choice()
- shuffle()
- sample()
- random()

#### import library

In [13]:
import random as rd

### randrange()

In [64]:

print(rd.randrange(3, 9))

3


### randint()

In [69]:
print(rd.randint(3, 9))  #end value include


3


### choice()

- The choice() method returns a randomly selected element from the specified sequence.

- The sequence can be a string, a range, a list, a tuple or any other kind of sequence.

In [6]:
mylist = ["apple", "banana", "cherry"]

print(rd.choice(mylist))

apple


### shuffle()

In [20]:
m = ["apple", "banana", "cherry"]

rd.shuffle(m)
print(m)

['cherry', 'apple', 'banana']


### sample()

In [27]:
# example

m1 = ["apple", "banana", "cherry"]

print(rd.sample(m1,2))

['apple', 'banana']


### random()

In [35]:
print(rd.random())

0.10101958518746335


In [7]:
#+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

### Arithmetic Operations in Numpy

- add()
- subtract()
- multiply()
- divide()

In [2]:
50*15

750